words_list = {
    "animals": [
        "dog", "cat", "elephant", "penguin", "tiger", "lion", "giraffe",
        "zebra", "cheetah", "rhinoceros", "hippopotamus", "kangaroo", "koala",
        "crocodile", "elephant seal", "hyena", "wolf", "fox", "bear", "deer",
        "moose", "buffalo", "goat", "sheep", "rabbit", "monkey",
        "gorilla", "chimpanzee", "lemur"
    ],
    "verbs": [
        "run", "jump", "walk", "talk", "eat", "sleep", "sing", "dance", "read",
        "write", "study", "work", "play", "think", "laugh", "cry", "swim",
        "climb", "drive", "fly", "smile", "fight", "paint", "cook", "drink",
        "listen", "speak", "teach"
    ],
    "uncommon words": [
        "onomatopoeia", "serendipity", "nebulous", "mellifluous", "ephemeral",
        "resplendent", "euphoric", "petrichor", "ethereal", "quixotic",
        "susurrus", "vestige", "limerence", "incandescent", "halcyon",
        "luminous", "epiphany", "ineffable", "penumbra", "sonder",
        "iridescent", "solitude", "phosphenes", "seraphic", "effervescence",
        "cynosure", "idyllic"
    ]
}


definitions = {
    "dog": "A domesticated animal, typically loyal and friendly.",
    "cat": "A domesticated animal, known for being independent and agile.",
    "elephant": "A large herbivorous mammal with a trunk and tusks.",
    "penguin": "A flightless aquatic bird with black and white plumage.",
    "tiger": "A large predatory cat with orange coat and black stripes.",
    "lion": "Majestic carnivorous feline known for its mane.",
    "giraffe": "Tallest living terrestrial animal with a long neck.",
    "zebra": "Striped African equine resembling a horse.",
    "cheetah": "Fastest land animal with distinctive spots.",
    "rhinoceros": "Large herbivorous mammal with one or two horns.",
    "hippopotamus": "Hefty semi-aquatic herbivore.",
    "kangaroo": "Hopping marsupial with a pouch.",
    "koala": "Marsupial known for eating eucalyptus leaves.",
    "crocodile": "Large predatory reptile found near water.",
    "elephant seal": "Massive marine mammal with a trunk-like nose.",
    "hyena": "Nocturnal scavenger with distinct vocalizations.",
    "wolf": "Social predator, a close relative of dogs.",
    "fox": "Small carnivorous mammal known for its cunning.",
    "bear": "Large omnivorous mammal capable of hibernation.",
    "deer": "Graceful herbivore with antlers.",
    "moose": "Large antlered animal of the deer family.",
    "buffalo": "Massive horned grazer found in grasslands.",
    "goat": "Domesticated hoofed mammal known for climbing.",
    "sheep": "Domesticated woolly ruminant.",
    "rabbit": "Small mammal known for its hopping.",
    "monkey": "Playful arboreal primate with a prehensile tail.",
    "gorilla": "Gentle giant ape, the largest of the primates.",
    "chimpanzee": "Highly intelligent and social primate.",
    "lemur": "Primate endemic to Madagascar known for its large eyes.",
    "run": "To move swiftly on foot.",
    "jump": "To push off the ground with one's feet.",
    "walk": "Move on foot.",
    "talk": "Speak to someone.",
    "eat": "Consume food.",
    "sleep": "To rest.",
    "sing": "Produce musical sounds with the voice.",
    "dance": "Move rhythmically to music.",
    "read": "Look at and comprehend written words.",
    "write": "Mark letters or words on a surface.",
    "study": "Examine and learn.",
    "work": "Engage in activity for payment.",
    "play": "Engage in activity for enjoyment.",
    "think": "Mentally consider or reason.",
    "laugh": "Make the sounds and movements of laughter.",
    "cry": "Shed tears as an expression of emotion.",
    "swim": "Move through water by bodily movements.",
    "climb": "Move upwards using hands and feet.",
    "drive": "Operate a vehicle.",
    "fly": "Move through the air using wings or aircraft.",
    "smile": "Form one's features into a pleased expression.",
    "fight": "Engage in a physical confrontation.",
    "paint": "Apply color to a surface.",
    "cook": "Prepare food for eating.",
    "drink": "Consume liquid.",
    "listen": "Perceive sound with ears.",
    "speak": "Articulate words verbally.",
    "teach": "Impart knowledge or skill.",
    "onomatopoeia": "The formation of a word from a sound.",
    "serendipity": "The occurrence of events by chance.",
    "nebulous": "Hazy or unclear.",
    "mellifluous": "Smooth, sweet, or musical.",
    "ephemeral": "Lasting for a very short time.",
    "resplendent": "Shining brightly or attractively.",
    "euphoric": "Intensely happy or confident.",
    "petrichor": "The pleasant smell after rain.",
    "ethereal": "Delicate or light in a way that seems other-wordly.",
    "quixotic": "Extremely idealistic, unrealistic, and impractical.",
    "susurrus": "Whispering, murmuring, or rustling.",
    "vestige": "A remnant of something that no longer exists.",
    "limerence": "The state of being infatuated with another person.",
    "incandescent": "Emitting bright light as a result of being heated.",
    "halcyon": "A time in the past that was idyllically happy and peaceful.",
    "luminous": "Glowing or emitting light.",
    "epiphany": "A sudden and profound realization.",
    "ineffable": "Too great or extreme to be expressed or described in words.",
    "penumbra": "A partially shaded area around the edges of a shadow.",
    "sonder": "Realising people have vivid and complex lives as you.",
    "iridescent": "Luminous colors that change from different angles.",
    "solitude": "The state or situation of being alone.",
    "phosphenes": "Sensation of seeing light without light entering the eye.",
    "seraphic": "Beautiful or pure like an angel.",
    "effervescence": "Bubbling or fizzing, lively and enthusiastic.",
    "cynosure": "Something that attracts attention or admiration.",
    "idyllic": "Extremely pleasant, peaceful, or picturesque."
}
